### PR TITLE
Add cling — C++ interpreter

### PR DESCRIPTION
**Pull request by AlesTsurko**

### CODE REVIEW

**Comment by metakirby5** [comment]
Thanks! Would you also mind updating:

- `README.md`:
  - Line after "Languages with built-in support:"
- `doc/codi.txt`:
  - Table in *codi-interpreters-defaults*

**Comment by metakirby5** [comment]
Also - which version of `cling` are you using? Mine does not seem to support ctrl-D to exit, which is required for Codi to properly work.

**Comment by AlesTsurko** [comment]
Looks like cling doesn't support Ctrl-D at all... But it supports Ctrl-C.
BTW, it would be better to provide a quit command with another interpreter setups. Something like:

```
{
  'python': {
     'bin': 'python',
     'prompt': ...,
     'quitcmd': 'quit()'
  },
  'cpp': {
     'bin': 'cling',
     'prompt': ...,
     'quitcmd': '.q'
  },
  etc.
}
```
Or it cause a lot of refactoring?

**Comment by AlesTsurko** [comment]
Is that do the job?

**Comment by metakirby5** [comment]
Thanks for the changes! I'm not able to test it out at the moment, but it would be excellent if you could:

- Add some documentation about how to use this new feature
- Use `quitcmd` directly, instead of putting a newline before and after, in case newlines have undesirable side effects

**Comment by AlesTsurko** [comment]
Regarding docs — I could try, but my knowledge of English is bad for that... So I'm not sure:D

Is it safe to pass the newlines? I've found that you've used a newline in the `magic` variable. Also the `quitcmd` is entering on a new line (as with a standard expression), so if there is no a newline at the end of the previous expression, the `quitcmd` will concatenate with the previous expression. For example, if I'll enter `2+2` and there will not be a newline at the end, the resulting part of the string with `'quitcmd': 'quit()'` (for python) will be: 
```
"2+2 quit()"
```
or in the worst case:
```
"2+2quit()"
```

But regarding to the last `quitcmd`'s newline token — maybe it would be better to change it to `<cr>` (as in the `magic`)?
```
let input = input."\n".i['quitcmd']."<cr>"
``` 
or at all
```
let input = input."\n<cr>\n".i['quitcmd']."<cr>"
```
This should act as a replacement to the `magic` (the `quitcmd` is like `<C-d>`, but it's a standard interpreter input (as an expression)).

**Comment by metakirby5** [comment]
Good point with the undesired expression concatenation. I agree with you now, that the first newline should be kept. `'quitcmd': 'quit()'` is quite a bit more elegant as well, so I think I'm fine with the change!

Regarding docs, just a sentence or two should be fine. I can fix it up after merging :)

**Pull request merged**
