### PR TITLE
Add lua support

### PR DESCRIPTION
**Pull request by dbrodie**
Tested and seems to work by me, hope I didn't miss anything.

### CODE REVIEW

**Comment by metakirby5** [comment]
Looks good! I'll test it out when I get home, but in the meantime, could you please add documentation [as per CONTRIBUTING.md](https://github.com/metakirby5/codi.vim/blob/master/CONTRIBUTING.md#adding-new-language-support)?

Thank you for contributing ❤️

**Comment by dbrodie** [comment]
No problem. Sorry, I missed the contributing file.

You might want to update it to point at the correct location for `s:codi_default_interpreters`.

**Comment by metakirby5** [comment]
RE: `s:codi_default_interpreters`, will do.

I got to try out the interpreter, and I discovered that values are only printed if a `=` or `return` is prepended to the line. Could you add a note about this to the `Notes` section of the table in `codi.txt`?

Thanks!

**Comment by dbrodie** [comment]
That's very weird, that's not what I saw.
screenshot from 2016-09-22 15-53-42

The only problem I saw is that if you do a local variable in lua in the top level it loses scope, that should be worthwhile to add.

**Comment by metakirby5** [comment]
What version of `lua` do you have? I'm using `Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio`, which gives me a syntax error on `x + 7` as well.

**Comment by dbrodie** [comment]
Yeah, that's the problem, I was using lua 5.3.3, this is one of the changes there. I'll add that to the documentation, and mention that it is only for lua < 5.3.
In the future, it might be a good idea to use [lua-repl](https://github.com/hoelzro/lua-repl).

Thanks for the catch.

**Comment by metakirby5** [comment]
Sure. I think just `lua` will be the better choice here, since not all users will have `lua-repl`. You can just note that for lua < 5.3, you will need to prepend `=` or `return` to raw expressions.

**Pull request merged**
