### PR TITLE
fix Python's IndentationError issue

### PR DESCRIPTION
**Pull request by heshiyou**
Insert # in the blank lines above Python's class methods definition to avoid `IndentationError`

### CODE REVIEW

**Comment by metakirby5** [comment]
Looks like you're using ruby's rephrase function - would you mind using a separate function dedicated to python, as to not mess up ruby functionality?

**Comment by heshiyou** [comment]
@metakirby5 sure, gonna do it.

**Comment by heshiyou** [comment]
@metakirby5 done. Please review.

**Comment by heshiyou** [comment]
@metakirby5 I found a way to make it as smooth as possible: you can insert blank line anywhere you like and it works just fine.
Gonna tweak the code and doc and please review when I'm done.

**Comment by heshiyou** [comment]
@metakirby5 Done.

**Comment by heshiyou** [comment]
@metakirby5 Any questions about this pr?

**Comment by metakirby5** [comment]
Sorry I haven't been able to take a look yet. It's project crunch time + midterm season. I'll get around to this when I can :)

**Comment by metakirby5** [comment]
Looks good - thanks!

**Pull request merged**
