### PR TITLE
Add initial support for Julia

### PR DESCRIPTION
**Pull request by originalsouth**
Hi, I added support for Julia, the only thing that is broken now is that it the first line isn't parsed; and hence codi is of by one line. Cheers!

### CODE REVIEW

**Comment by metakirby5** [comment]
Hi, thanks for contributing!

Please add relevant documentation to the
following places:

- `README.md`:
  - Line after "Languages with built-in support:"
  - Line after "Default interpreter dependencies:"
- `doc/codi.txt`:
  - Table in *codi-interpreters-defaults*

What do you mean by the first line isn't parsed? Curious to see if it's a quick fix.

**Comment by originalsouth** [comment]
Hi, thank you, my pleasure. 

I changed the documentation and README.md as requested.

> What do you mean by the first line isn't parsed? Curious to see if it's a quick fix.

The first line of a julia script doesn't show up in the codi screen. The first line of the of the codi screen is the second line of the julia script etc. See screenshot for an illustration:
screenshot_2017-06-06_23-31-27

Not exactly sure what causes this behavior but it might have to do with Julia printing a newline after every output.

Cheers!

**Comment by originalsouth** [comment]
Capturing the Julia prompt resolves the line mismatch issue.

**Comment by metakirby5** [comment]
Awesome, thanks for the fix! Merging :)

**Pull request merged**
